server {
    listen 80;
    server_name localhost;

    # Esto sirve tu aplicación de Angular
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # Vital para que funcione el router de Angular
    }

    # Esto redirige las peticiones /api hacia tu contenedor del Backend
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
