spring.application.name=matricula-service
server.port=8080

# Conexion MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/matricula_colegio_db?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true