version: '3.8'

services:
  # Base de Datos
  db:
    image: mysql:8.0
    container_name: matricula_db
    restart: always
    environment:
      MYSQL_DATABASE: matricula_colegio_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Tu Backend (Spring Boot)
  backend:
    build: .
    container_name: matricula_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/matricula_colegio_db?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      # ESTA CLAVE DEBE SER LA MISMA QUE LA DE ARRIBA:
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SERVER_PORT=8080
    depends_on:
      - db

volumes:
  db_data:
